In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import html5lib

In [2]:
#Read in a list of 2000+ positive words
pos_words_loc = ('https://github.com/gurkpet/Thinkful-Lessons/blob/master/'
             'Thinkful%202.2.7-Naive%20Bayes/Word%20Lists/positive-words.txt')
pos_words_list = pd.read_html(pos_words_loc, skiprows=35)

#clean up the read in by removing the first column of junk data
for row in pos_words_list:
   del row[0]    

#convert list into dataframe
pos_words = pd.DataFrame(pos_words_list[0])

In [3]:
list_pos_words = list(pos_words[1])

In [25]:
def testaccuracy(target, data):
    # Our data is binary / boolean, so we're importing the Bernoulli classifier.
    from sklearn.naive_bayes import BernoulliNB

    # Instantiate our model and store it in a new variable.
    bnb = BernoulliNB()

    # Fit our model to the data.
    bnb.fit(data, target)

    pred = bnb.predict(data)

    print('Out of {} predictions, {} were misclassified'.format(data.shape[0], (pred != target).sum()))
    accuracy = (data.shape[0]-(pred != target).sum())/data.shape[0]
    print('Thats a {0:.2} accuracy'.format(accuracy))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(target, pred))

In [19]:
#read in amazon file
amzn_file_loc = ('https://raw.githubusercontent.com/gurkpet/Thinkful-Lessons/master/'
            'Thinkful%202.2.7-Naive%20Bayes/amazon_cells_labelled.txt')

amzn_dat = pd.read_csv(amzn_file_loc, delimiter= '\t', header=None)
#rename column headers
amzn_dat.columns = ['review', 'positive_review']
amzn_target = amzn_dat['positive_review']

In [20]:
for key in list_pos_words:
    amzn_dat[str(key)] = amzn_dat.review.str.contains(str(key), case = False)
amzn_dat['positive_review'] = (amzn_dat['positive_review'] == 1)
data_amzn = amzn_dat[list_pos_words]
amzn_target = amzn_dat['positive_review']

In [27]:
testaccuracy(amzn_target, data_amzn)

Out of 1000 predictions, 166 were misclassified
Thats a 0.83 accuracy
[[455  45]
 [121 379]]


In [64]:
amzn_dat

review positive_review     a+  \
0    So there is no way for me to plug it in here i...           False   True   
1                          Good case, Excellent value.            True   True   
2                               Great for the jawbone.            True   True   
3    Tied to charger for conversations lasting more...           False   True   
4                                    The mic is great.            True   True   
5    I have to jiggle the plug to get it to line up...           False   True   
6    If you have several dozen or several hundred c...           False   True   
7          If you are Razr owner...you must have this!            True   True   
8                  Needless to say, I wasted my money.           False   True   
9                     What a waste of money and time!.           False   True   
10                     And the sound quality is great.            True   True   
11   He was very impressed when going from the orig...            True   True   
12   If the two were seperated by a mere 5+ ft I st...           False   True   
13                            Very good quality though            True   True   
14   The design is very odd, as the ear "clip" is n...           False   True   
15   Highly recommend for any one who has a blue to...            True   True   
16                 I advise EVERYONE DO NOT BE FOOLED!           False   True   
17                                    So Far So Good!.            True   True   
18                                       Works great!.            True   True   
19   It clicks into place in a way that makes you w...           False   True   
20   I went on Motorola's website and followed all ...           False   True   
21   I bought this to use with my Kindle Fire and a...            True   True   
22            The commercials are the most misleading.           False   True   
23   I have yet to run this new battery below two b...            True   True   
24   I bought it for my mother and she had a proble...           False   True   
25                Great Pocket PC / phone combination.            True   True   
26   I've owned this phone for 7 months now and can...            True   True   
27   I didn't think that the instructions provided ...           False   True   
28   People couldnt hear me talk and I had to pull ...           False   True   
29                                Doesn't hold charge.           False   True   
..                                                 ...             ...    ...   
970  I plugged it in only to find out not a darn th...           False   True   
971                                 Excellent product.            True  False   
972                        Earbud piece breaks easily.           False   True   
973                                     Lousy product.           False  False   
974  This phone tries very hard to do everything bu...           False   True   
975  It is the best charger I have seen on the mark...            True   True   
976                                  SWEETEST PHONE!!!            True  False   
977             :-)Oh, the charger seems to work fine.            True   True   
978  It fits so securely that the ear hook does not...            True   True   
979                                 Not enough volume.           False  False   
980                Echo Problem....Very unsatisfactory           False   True   
981  you could only take 2 videos at a time and the...           False   True   
982                            don't waste your money.           False   True   
983  I am going to have to be the first to negative...           False   True   
984  Adapter does not provide enough charging current.           False   True   
985  There was so much hype over this phone that I ...           False   True   
986  You also cannot take pictures with it in the c...           False   True   
987                            Phone falls out easily.           False   True  

In [57]:
from sklearn.decomposition import PCA 
def doeigen(data, components):
    X = data.ix[:,2:components+2]
    sklearn_pca = PCA(n_components=components)
    Y_sklearn = sklearn_pca.fit_transform(X)
    Xt = X.T
    Cx = np.cov(Xt)
    pd.DataFrame(Cx)

    # Calculating eigenvalues and eigenvectors.
    eig_val_cov, eig_vec_cov = np.linalg.eig(Cx)

    # Inspecting the eigenvalues and eigenvectors.
    for i in range(len(eig_val_cov)):
        eigvec_cov = eig_vec_cov[:, i].reshape(1, components).T
        print('Eigenvector {}: \n{}'.format(i + 1, eigvec_cov))
        print('Eigenvalue {}: {}'.format(i + 1, eig_val_cov[i]))
        print(40 * '-')

In [62]:
for x in range(15):
    count = x*2+2
    print('\nEigenvalue for {} components'.format(count))
    doeigen(amzn_dat, count)


Eigenvalue for 2 components
Eigenvector 1: 
[[ 0.99999936]
 [ 0.00113282]]
Eigenvalue 1: 0.09643255489968727
----------------------------------------
Eigenvector 2: 
[[-0.00113282]
 [ 0.99999936]]
Eigenvalue 2: 0.0009998775327449746
----------------------------------------

Eigenvalue for 4 components
Eigenvector 1: 
[[ 0.99999936]
 [ 0.00113282]
 [ 0.        ]
 [ 0.        ]]
Eigenvalue 1: 0.0964325548996872
----------------------------------------
Eigenvector 2: 
[[-0.00113282]
 [ 0.99999936]
 [ 0.        ]
 [ 0.        ]]
Eigenvalue 2: 0.0009998775327449759
----------------------------------------
Eigenvector 3: 
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]
Eigenvalue 3: 0.0
----------------------------------------
Eigenvector 4: 
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
Eigenvalue 4: 0.0
----------------------------------------

Eigenvalue for 6 components
Eigenvector 1: 
[[-0.99999872]
 [-0.00113281]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.00113281]]
Eigenvalue 1: 0.09643267736405885
-------------